name: Build PFC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.0.x', '6.0.x'  ]
        
    steps:
    - name: Checks
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies
      run: |
        dotnet build PowerFlowCore/PowerFlowCore.csproj --verbosity q
        dotnet build PowerFlowCore.Samples/PowerFlowCore.Samples.csproj --verbosity q
        
      
    - name: Build
      run: |
        dotnet build PowerFlowCore/PowerFlowCore.csproj --configuration Release --no-restore --verbosity q
        dotnet build PowerFlowCore.Samples/PowerFlowCore.Samples.csproj --configuration Release --no-restore --verbosity q
