name: Build PFC

on:
  push:
    branches: [ "dev", "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x', '6.0.x'  ]
        
    steps:
    - name: Checks
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build PowerFlowCore/PowerFlowCore.csproj --configuration Release --no-restore
      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
